# Generated by Django 5.1.2 on 2024-10-12 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('number_of_orders', models.IntegerField(default=0)),
                ('stock1', models.IntegerField(default=0)),
                ('stock2', models.IntegerField(default=0)),
                ('stock3', models.IntegerField(default=0)),
                ('stock4', models.IntegerField(default=0)),
                ('stock5', models.IntegerField(default=0)),
                ('stock6', models.IntegerField(default=0)),
                ('stock7', models.IntegerField(default=0)),
                ('stock8', models.IntegerField(default=0)),
                ('stock9', models.IntegerField(default=0)),
                ('stock10', models.IntegerField(default=0)),
                ('stock11', models.IntegerField(default=0)),
                ('stock12', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
