# Generated by Django 5.1.2 on 2024-10-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='stock10',
        ),
        migrations.RemoveField(
            model_name='player',
            name='stock11',
        ),
        migrations.RemoveField(
            model_name='player',
            name='stock12',
        ),
        migrations.RemoveField(
            model_name='player',
            name='stock9',
        ),
    ]
