# Generated by Django 5.1.2 on 2024-10-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_system', '0004_alter_player_number_of_orders_alter_player_stock1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_text', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
