# Generated by Django 5.1.2 on 2024-10-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_system', '0005_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='Title here', max_length=100),
        ),
    ]
