# Generated by Django 5.1.2 on 2024-10-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_system', '0006_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=20000, max_digits=10),
        ),
    ]
