# Generated by Django 5.1.2 on 2024-10-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_system', '0007_alter_player_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upper_cap', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('lower_cap', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
            ],
        ),
    ]
