# Generated by Django 5.1.2 on 2024-10-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_system', '0011_sitesetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={},
        ),
    ]
