# Generated by Django 5.1.2 on 2024-10-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_system', '0013_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='net_worth',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
