# Generated by Django 5.1.2 on 2024-10-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_system', '0014_alter_leaderboard_net_worth'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
